# Generated by Django 5.0.1 on 2024-03-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cost', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cart_table',
            },
        ),
        migrations.CreateModel(
            name='ignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phno', models.CharField(max_length=16, unique=True)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': '123_table',
            },
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phno', models.CharField(max_length=16, unique=True)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'signup_table',
            },
        ),
    ]
