# Generated by Django 5.0.1 on 2024-03-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ignup',
        ),
    ]
